"""Database persistence API for FinAlly."""

from app.db.repository import (
    DEFAULT_CASH_BALANCE,
    DEFAULT_USER_ID,
    DEFAULT_WATCHLIST,
    add_watchlist_ticker,
    delete_position,
    get_connection,
    get_position,
    get_user_profile,
    init_db,
    insert_chat_message,
    insert_portfolio_snapshot,
    insert_trade,
    list_chat_messages,
    list_portfolio_snapshots,
    list_positions,
    list_trades,
    list_watchlist,
    remove_watchlist_ticker,
    update_cash_balance,
    upsert_position,
    utc_now_iso,
)

__all__ = [
    "DEFAULT_CASH_BALANCE",
    "DEFAULT_USER_ID",
    "DEFAULT_WATCHLIST",
    "add_watchlist_ticker",
    "delete_position",
    "get_connection",
    "get_position",
    "get_user_profile",
    "init_db",
    "insert_chat_message",
    "insert_portfolio_snapshot",
    "insert_trade",
    "list_chat_messages",
    "list_portfolio_snapshots",
    "list_positions",
    "list_trades",
    "list_watchlist",
    "remove_watchlist_ticker",
    "update_cash_balance",
    "upsert_position",
    "utc_now_iso",
]
